// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otkziexpqwvefkdtbyxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a3ppZXhwcXd2ZWZrZHRieXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzQzMTMsImV4cCI6MjA3NDExMDMxM30.SDlbiNVi9FH9QNwcM7LQ-yQdnbgplIjqMIIz1OIXmEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});